# Generated by Django 5.2.6 on 2026-04-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('role', models.CharField(max_length=150, verbose_name='Chức vụ')),
                ('bio', models.TextField(verbose_name='Mô tả ngắn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='leadership/', verbose_name='Ảnh')),
                ('initials', models.CharField(blank=True, max_length=10, verbose_name='Chữ viết tắt')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn URL')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
