# Generated by Django 5.2.6 on 2026-04-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_leadershipmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề')),
                ('statement_type', models.CharField(choices=[('vision', 'Tầm nhìn'), ('mission', 'Sứ mệnh')], max_length=20, verbose_name='Loại nội dung')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('icon', models.CharField(blank=True, default='fa-star', help_text='Ví dụ: fa-eye, fa-rocket', max_length=50, verbose_name='Icon Font Awesome')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['statement_type', 'order', 'created_at'],
            },
        ),
    ]
