# Generated by Django 5.2.6 on 2026-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Hình ảnh chứng chỉ'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.CharField(choices=[('fa-certificate', 'Giấy chứng nhận'), ('fa-shield', 'Shield'), ('fa-leaf', 'Leaf'), ('fa-building-o', 'Building'), ('fa-trophy', 'Trophy'), ('fa-star', 'Star'), ('fa-check-circle', 'Check Circle'), ('fa-globe', 'Globe')], default='fa-certificate', max_length=50, verbose_name='Icon'),
        ),
    ]
