# Generated by Django 5.2.6 on 2026-04-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_consultation_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='consultation',
            name='budget',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consultation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='consultation',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='consultation',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='project_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='consultation',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
