# Generated by Django 5.2.6 on 2026-04-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_consultation_options_consultation_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='project_type',
            field=models.CharField(choices=[('dan-dung', 'Xây dựng Dân dụng (Nhà ở, Biệt thự, Chung cư)'), ('cong-nghiep', 'Xây dựng Công nghiệp (Nhà máy, Kho xưởng)'), ('thuong-mai', 'Xây dựng Thương mại (Văn phòng, TTTM)'), ('ha-tang', 'Hạ tầng Kỹ thuật (Đường, Cầu, Cống)'), ('noi-that', 'Thi công Nội thất'), ('thiet-ke', 'Thiết kế Kiến trúc & Kết cấu'), ('khac', 'Khác')], default='', max_length=50),
        ),
    ]
