# Generated by Django 5.2.6 on 2026-04-17 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_project_is_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='side',
        ),
    ]
