# Generated by Django 5.2.6 on 2026-04-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_certificate_options_remove_certificate_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kicker', models.CharField(default='Thành lập 2009', max_length=100, verbose_name='Dòng nhỏ trên cùng')),
                ('brand_name', models.CharField(default='Sao Bắc Đẩu', max_length=200, verbose_name='Tên thương hiệu')),
                ('slogan', models.CharField(default='Chất lượng — Uy tín — Bền vững', max_length=300, verbose_name='Slogan')),
                ('highlight_1', models.CharField(blank=True, max_length=100, verbose_name='Highlight 1 (vd: ISO 9001:2015)')),
                ('highlight_2', models.CharField(blank=True, max_length=100, verbose_name='Highlight 2 (vd: 200+ kỹ sư)')),
                ('highlight_3', models.CharField(blank=True, max_length=100, verbose_name='Highlight 3 (vd: Thi công toàn quốc)')),
                ('badge_number', models.CharField(default='500+', max_length=20, verbose_name='Số badge (vd: 500+)')),
                ('badge_text', models.CharField(default='Dự Án Hoàn Thành', max_length=100, verbose_name='Chữ dưới badge')),
                ('heading', models.CharField(default='Công Ty Xây Dựng Sao Bắc Đẩu', max_length=300, verbose_name='Tiêu đề lớn')),
                ('paragraph_1', models.TextField(verbose_name='Đoạn văn 1')),
                ('paragraph_2', models.TextField(blank=True, verbose_name='Đoạn văn 2')),
                ('bullet_points', models.TextField(help_text='Mỗi dòng là một bullet. VD: Chứng nhận ISO 9001:2015', verbose_name='Danh sách điểm mạnh')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Giới thiệu công ty',
            },
        ),
    ]
