# Generated by Django 5.2.6 on 2026-04-17 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_aboutstatementtype_and_refactor_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên loại')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Loại dịch vụ',
                'verbose_name_plural': 'Loại dịch vụ',
                'ordering': ['order', 'created_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Tiêu đề')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('icon', models.CharField(blank=True, default='', help_text='Có thể nhập fa-eye, fa-solid fa-eye, cart-arrow-down hoặc URL icon từ Font Awesome.', max_length=500, verbose_name='Icon Font Awesome / Icon URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='home.servicetype', verbose_name='Loại dịch vụ')),
            ],
            options={
                'verbose_name': 'Dịch vụ',
                'verbose_name_plural': 'Dịch vụ',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
