# Generated by Django 5.2.6 on 2026-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_merge_0015_aboutintro_0015_servicetype_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier_address",
            field=models.TextField(
                blank=True, default="", verbose_name="Địa chỉ nhà cung cấp / công ty"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_map_embed_url",
            field=models.URLField(
                blank=True, verbose_name="Link Google Maps của nhà cung cấp / công ty"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="supplier_name",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Tên nhà cung cấp / công ty",
            ),
        ),
    ]
