# Generated by Django 5.2.6 on 2026-04-18 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_supplier_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeWhyChooseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(default='Tại Sao Chọn Sao Bắc Đẩu?', max_length=255, verbose_name='Tiêu đề khối bên trái')),
                ('right_kicker', models.CharField(default='SBD Construction', max_length=100, verbose_name='Dòng nhỏ bên phải')),
                ('right_title', models.CharField(default='Thi công trọn gói', max_length=255, verbose_name='Tiêu đề lớn bên phải')),
                ('right_subtitle', models.CharField(default='Dân dụng • Công nghiệp • Hạ tầng', max_length=255, verbose_name='Dòng mô tả bên phải')),
                ('badge_number', models.CharField(default='15+', max_length=20, verbose_name='Số badge')),
                ('badge_label', models.CharField(default='Năm Kinh Nghiệm', max_length=100, verbose_name='Chữ dưới badge')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Khối Tại Sao Chọn Chúng Tôi',
                'verbose_name_plural': 'Khối Tại Sao Chọn Chúng Tôi',
            },
        ),
        migrations.CreateModel(
            name='HomeWhyChooseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-solid fa-star', help_text='Ví dụ: fa fa-trophy hoặc fa-solid fa-shield', max_length=100, verbose_name='Icon Font Awesome')),
                ('title', models.CharField(max_length=255, verbose_name='Tiêu đề item')),
                ('content', models.TextField(verbose_name='Nội dung item')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.homewhychoosesection', verbose_name='Khối')),
            ],
            options={
                'verbose_name': 'Lý do chọn chúng tôi',
                'verbose_name_plural': 'Lý do chọn chúng tôi',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
