# Generated by Django 5.2.6 on 2026-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_aboutvideotour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đối tác')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logo')),
                ('website_url', models.URLField(blank=True, verbose_name='Website')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
