# Generated by Django 5.2.5 on 2026-05-05 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, default='Sao Bac Dau Construction', max_length=150, verbose_name='Tên hiển thị email gửi OTP')),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email gửi OTP')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP host')),
                ('smtp_port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP username')),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255, verbose_name='SMTP password / app password')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Dùng TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='Dùng SSL')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình email OTP',
                'verbose_name_plural': 'Cấu hình email OTP',
            },
        ),
        migrations.CreateModel(
            name='PasswordOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email nhận OTP')),
                ('purpose', models.CharField(choices=[('forgot_password', 'Quên mật khẩu'), ('change_password', 'Đổi mật khẩu')], max_length=30)),
                ('code', models.CharField(max_length=6, verbose_name='Mã OTP')),
                ('expires_at', models.DateTimeField(verbose_name='Hết hạn lúc')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP đổi mật khẩu',
                'verbose_name_plural': 'OTP đổi mật khẩu',
                'ordering': ['-created_at'],
            },
        ),
    ]
