# Generated by Django 5.2.6 on 2026-05-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_emailotpsettings_passwordotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationSpaceDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề')),
                ('summary', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Nội dung chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='education_spaces/', verbose_name='Ảnh minh họa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Thiết kế không gian giáo dục',
                'verbose_name_plural': 'Thiết kế không gian giáo dục',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OfficeRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tên văn phòng')),
                ('summary', models.TextField(blank=True, verbose_name='Mô tả ngắn')),
                ('content', models.TextField(verbose_name='Thông tin chi tiết')),
                ('image', models.ImageField(blank=True, null=True, upload_to='office_rentals/', verbose_name='Ảnh văn phòng')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diện tích (m2)')),
                ('rent_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Giá thuê (VNĐ)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cho thuê văn phòng',
                'verbose_name_plural': 'Cho thuê văn phòng',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
