# Generated by Django 5.2.6 on 2026-05-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_educationspacedesign_officerental'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_type', models.CharField(choices=[('icon', 'Icon Font Awesome'), ('image', 'Hình ảnh')], default='icon', max_length=20, verbose_name='Kiểu logo')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='branding/', verbose_name='Ảnh logo')),
                ('logo_icon', models.CharField(blank=True, default='fa-solid fa-star', help_text='Có thể nhập fa-star, fa-solid fa-star, star hoặc link icon từ Font Awesome.', max_length=500, verbose_name='Tên class / link icon Font Awesome')),
                ('brand_name', models.CharField(default='Sao Bắc Đẩu', max_length=200, verbose_name='Tên thương hiệu')),
                ('brand_subtitle', models.CharField(default='Construction', max_length=200, verbose_name='Dòng phụ thương hiệu')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cấu hình thương hiệu',
                'verbose_name_plural': 'Cấu hình thương hiệu',
            },
        ),
    ]
