# Generated by Django 5.2.6 on 2026-05-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_sitebrandsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebrandsettings',
            name='footer_bottom_text',
            field=models.CharField(default='© 2026 Công Ty Xây Dựng Sao Bắc Đẩu | MST: 0123456789', max_length=300, verbose_name='Nội dung footer bottom'),
        ),
    ]
