# Generated by Django 5.2.6 on 2026-06-06 08:26

import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0028_sitebrandsettings_favicon_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('image', models.ImageField(upload_to=home.models.gallery_upload_path, verbose_name='Ảnh')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Ảnh thư viện',
                'verbose_name_plural': 'Ảnh thư viện',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='home_galler_content_f68aca_idx')],
            },
        ),
    ]
