# Generated by Django 5.2.6 on 2026-06-06 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationspacedesign',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='officerental',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='specializedservicecontent',
            name='image_mode',
            field=models.CharField(choices=[('single', 'Dùng 1 ảnh'), ('multiple', 'Dùng nhiều ảnh')], default='single', max_length=10),
        ),
    ]
