# Generated by Codex on 2026-07-12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0030_educationspacedesign_image_mode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLoginActivityAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_activity_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quyền xem lịch sử đăng nhập",
                "verbose_name_plural": "Quyền xem lịch sử đăng nhập",
            },
        ),
        migrations.CreateModel(
            name="StaffLoginActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Đang đăng nhập"),
                            ("logged_out", "Đã đăng xuất"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("login_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("device_label", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_login_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử đăng nhập staff/admin",
                "verbose_name_plural": "Lịch sử đăng nhập staff/admin",
                "ordering": ["-login_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "status"], name="home_staffl_user_id_75b251_idx"),
                    models.Index(fields=["session_key", "status"], name="home_staffl_session_863a6e_idx"),
                ],
            },
        ),
    ]
