# Generated by Codex on 2026-07-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0031_staff_login_activity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("custom_name", models.CharField(blank=True, default="", max_length=150)),
                ("browser_label", models.CharField(blank=True, default="", max_length=80)),
                ("platform_label", models.CharField(blank=True, default="", max_length=80)),
                ("device_type", models.CharField(blank=True, default="", max_length=40)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Thiết bị staff/admin",
                "verbose_name_plural": "Thiết bị staff/admin",
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="staffloginactivity",
            name="device",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="login_activities",
                to="home.staffdevice",
            ),
        ),
        migrations.AddField(
            model_name="staffloginactivity",
            name="device_identifier",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="staffloginactivity",
            name="device_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="staffdevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"),
                name="unique_staff_device_per_user",
            ),
        ),
    ]
