# Generated by Django 5.2.6 on 2026-07-21 16:53

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_staff_device'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sơ đồ nhân sự', max_length=200)),
                ('source_file', models.FileField(upload_to=home.models.staff_map_upload_path, verbose_name='File sơ đồ gốc')),
                ('image', models.ImageField(upload_to=home.models.staff_map_image_upload_path, verbose_name='Ảnh hiển thị')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sơ đồ vị trí staff/admin',
                'verbose_name_plural': 'Sơ đồ vị trí staff/admin',
                'ordering': ['-is_active', '-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffMapPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Tên vị trí')),
                ('x_percent', models.DecimalField(decimal_places=3, default=50, max_digits=6, verbose_name='Tọa độ ngang (%)')),
                ('y_percent', models.DecimalField(decimal_places=3, default=50, max_digits=6, verbose_name='Tọa độ dọc (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_map_positions', to=settings.AUTH_USER_MODEL, verbose_name='User được gán')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_map_positions', to=settings.AUTH_USER_MODEL)),
                ('staff_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='home.staffmap')),
            ],
            options={
                'verbose_name': 'Vị trí trên sơ đồ',
                'verbose_name_plural': 'Vị trí trên sơ đồ',
                'ordering': ['name', 'id'],
            },
        ),
    ]
