# Generated by Django 5.2.6 on 2026-09-23 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_staffmap_staffmapposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên đề mục')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Đề mục lớn dịch vụ',
                'verbose_name_plural': 'Đề mục lớn dịch vụ',
                'ordering': ['order', 'created_at', 'name'],
            },
        ),
        migrations.AddField(
            model_name='servicetype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_types', to='home.servicecategory', verbose_name='Đề mục lớn'),
        ),
    ]
