# Generated by Django 5.2.6 on 2026-09-23 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_servicecategory_servicetype_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Chữ thường'), ('bold', 'Chữ in đậm'), ('image', 'Ảnh')], default='text', max_length=20, verbose_name='Loại nội dung')),
                ('text', models.TextField(blank=True, default='', verbose_name='Nội dung chữ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/content_blocks/', verbose_name='Ảnh')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_blocks', to='home.service', verbose_name='Dịch vụ')),
            ],
            options={
                'verbose_name': 'Khối nội dung dịch vụ',
                'verbose_name_plural': 'Khối nội dung dịch vụ',
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
    ]
