# Generated by Django 5.2.6 on 2026-09-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_servicecontentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatingContactButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Tên nút')),
                ('action_type', models.CharField(choices=[('link', 'Mở đường link'), ('info', 'Hiện thông tin')], default='link', max_length=20, verbose_name='Kiểu hành động')),
                ('link_url', models.URLField(blank=True, verbose_name='Đường link')),
                ('info_text', models.TextField(blank=True, verbose_name='Thông tin hiển thị')),
                ('image', models.ImageField(upload_to='floating_contact_buttons/', verbose_name='Hình ảnh nút')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
                ('is_active', models.BooleanField(default=True, verbose_name='Hiển thị')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nút liên hệ nổi',
                'verbose_name_plural': 'Nút liên hệ nổi',
                'ordering': ['order', 'created_at', 'id'],
            },
        ),
    ]
