# Generated by Django 5.2.6 on 2026-10-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0036_floatingcontactbutton"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(default="Dịch vụ của Sao Bắc Đẩu", max_length=200, verbose_name="Tiêu đề trang")),
                ("hero_image", models.ImageField(blank=True, null=True, upload_to="services/hero/", verbose_name="Ảnh đại diện trang dịch vụ")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trang dịch vụ",
                "verbose_name_plural": "Trang dịch vụ",
            },
        ),
    ]
